[phases.setup]
providers = ["python310", "pipenv", "gcc", "nodejs", "npm"]

[phases.install]
cmds = ["echo installing python project dependencies...", "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy", "echo installation success"]
dependsOn = ["setup"]

[phases.build]
workdir = ["frontend"]
cmds = ["npm install", "npm run build", "echo build success"]
dependsOn = ["install"]

[phases.deploy]
cmds = ["echo starting server...", "python manage.py migrate", "echo theoritically, the server can be started now."]
dependsOn = ["build"]