providers = ["node", "python"]
[phases.setup]
nixPkgs = ["...", "ffmpeg"] # Install the ffmpeg package from Nix
aptPkgs = ["...", "wget"]   # Install the wget package with apt-get

providers = ["...", "python", "node"]

[phases.install]
cmds = ["echo installing python project dependencies...", "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy", "echo installation success"]

[phases.build]
cmds = ["echo building frontend...", "cd frontend/", "npm install", "npm run build", "echo build success"]
dependsOn = ["install"]

[phases.deploy]
cmds = ["echo starting server...", "python manage.py migrate", "echo theoritically, the server can be started now."]
dependsOn = ["build"]