[phases.setup]
providers = ["python310", "pipenv", "gcc", "nodejs", "npm"]

[phases.install]
cmds = ["echo installing python project dependencies...", "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy", "echo installation success"]
dependsOn = ["setup"]

[phases.build]
cmds = ["echo building front", "cd frontend && npm install && npm run build", "echo build success"]
dependsOn = ["install"]


[phases.start]
cmds = ["echo starting server...", "python manage.py migrate && python manage.py runserver", "echo server started"]
dependsOn = ["build"]